sudo: required
language: c

services:
  - docker

before_install:
  - docker info
  - docker build -t tomaer/alpine:edge .
  - docker build -t tomaer/alpine-arm:edge ARM/

script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push tomaer/alpine:edge;
    docker push tomaer/alpine-arm:edge;
    fi
