sudo: required
language: c

services:
  - docker

before_install:
  - docker info
  - docker build -f X64/gmt8-aliyun/Dockerfile -t tomaer/alpine:edge-gmt8-aliyun .
  - docker build -f X64/utc-aliyun/Dockerfile -t tomaer/alpine:edge-utc-aliyun .
  - docker build -f X64/gmt8/Dockerfile -t tomaer/alpine:edge-gmt8 .
  - docker build -f X64/utc/Dockerfile -t tomaer/alpine:edge-utc .
script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push tomaer/alpine:edge-gmt8-aliyun;
      docker push tomaer/alpine:edge-utc-aliyun;
      docker push tomaer/alpine:edge-gmt8;
      docker push tomaer/alpine:edge-utc;
    fi
